model:
  type: siren
  in_features: 3
  hidden_features: 128
  hidden_layers: 3
  out_features: 1
  first_w0: 15.0
  hidden_w0: 15.0

training:
  seed: 2024
  batch_size: 2048
  lr: 0.00005
  epochs: 1000
  checkpoint_epochs: [1, 2, 5, 10, 25, 50, 100, 200, 400, 600, 800, 1000]
  init_type: single
  init_checkpoint:

reconstruction:
  grid_res: 256
  grid_min: -0.5
  grid_max: 0.5
  grid_batch_size: 200000

evaluation:
  n_cube: 256
  n_pointcloud: 100000
  hash_resolution: 512

data:
  split: val

output:
  run_name: best_single_siren_w0_15_val_1000
