model:
  type: siren
  in_features: 3
  hidden_features: 128
  hidden_layers: 3
  out_features: 1
  first_w0: 15.0
  hidden_w0: 15.0

training:
  seed: 2024
  batch_size: 2048
  lr: 0.00005
  epochs: 200
  init_checkpoint: outputs/meta/meta_siren/meta_init.pt

reconstruction:
  grid_res: 256
  grid_min: -0.5
  grid_max: 0.5
  grid_batch_size: 200000

evaluation:
  n_cube: 256
  n_pointcloud: 100000
  hash_resolution: 512

data:
  split: test

output:
  run_name: batch_inr_siren_from_meta